version: 2
jobs:
  test:
    working_directory: ~/project
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          command: python -m unittest discover tests/

workflows:
  version: 2
  run-tests:
    jobs:
      - test
